server:
  port: 0
info:
  component: Patient User API
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
spring:
  profiles.active: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: consent2share@gmail.com
    password: fei@columbia
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  messages:
    basename: i18n/messages
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: patient-user
      client-secret: patient-user-secret
      access-token-uri: https://localhost:8443/uaa/oauth/token
    resource:
      jwt:
        keyValue:
                         -----BEGIN PUBLIC KEY-----
                         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0m59l2u9iDnMbrXHfqkO
                         rn2dVQ3vfBJqcDuFUK03d+1PZGbVlNCqnkpIJ8syFppW8ljnWweP7+LiWpRoz0I7
                         fYb3d8TjhV86Y997Fl4DBrxgM6KTJOuE/uxnoDhZQ14LgOU2ckXjOzOdTsnGMKQB
                         LCl0vpcXBtFLMaSbpv1ozi8h7DJyVZ6EnFQZUWGdgTMhDrmqevfx95U/16c5WBDO
                         kqwIn7Glry9n9Suxygbf8g5AzpWcusZgDLIIZ7JTUldBb8qU2a0Dl4mvLZOn4wPo
                         jfj9Cw2QICsc5+Pwf21fP+hzf+1WSRHbnYv8uanRO0gZ8ekGaghM/2H6gqJbo2nI
                         JwIDAQAB
                         -----END PUBLIC KEY-----
      user-info-uri: https://localhost:8443/uaa/userinfo
mhc:
  apis:
    pp-ui: https://localhost/pp-ui
    scim: https://localhost:8443/uaa
  patient-user:
    config:
      pp-ui-verification-relative-path: "/fe/account/verification#emailToken="
      email-token-expiration-in-days: 7
logging:
  file: /java/MHC_LOGS/patient-user/patient-user.log
  level:
    org.springframework.security: debug
---
spring.profiles: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient-user?autoReconnect=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    validation-query: select 1
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 1800000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
---
spring.profiles: h2
spring:
  datasource:
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

---
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://patient-user-db.mhc.com:3306/patient-user?autoReconnect=true
security:
  oauth2:
    client:
      access-token-uri: https://uaa.mhc.com:8443/uaa/oauth/token
    resource:
      user-info-uri: https://uaa.mhc.com:8443/uaa/userinfo
mhc:
  apis:
    pp-ui: https://pp-ui.mhc.com/pp-ui
    scim: https://uaa.mhc.com:8443/uaa
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true
---
spring.profiles: ssl
server:
  port: 8452
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /patientUser
