# SSL is disabled by default for the Patient User to make development environment setup easier.
# YOU MUST ENABLE SSL IN AN ACTUAL DEPLOYMENT ENVIRONMENT!
#
# To enable SSL for the Patient User:
#   1) Activate the 'ssl' spring profile by passing in the following program argument:
#          a) --spring.profiles.active=ssl
#   2) Set the appropriate values for the 'server.ssl.key-store' and 'server.ssl.key-store-password' properties.
#          a) You can override/set these properties by setting them in an externalzied application.yml file.
#               EXAMPLE:
#                  server:
#                     ssl:
#                        key-store: /ssl_keystore.keystore
#                        key-store-password: changeit
#          b) Alternatively, you can pass the properties in using the following program arguments:
#                 i) --server.ssl.key-store=path-to-file/filename
#                ii) --server.ssl.key-store-password=your-keystore-password
server:
  port: 8452
logging:
  file: /java/C2S_LOGS/patient-user/patient-user.log
info:
  component: Patient User API
# TODO: enable feign hystrix back when PHR API is refactored to a service that can be called by this API without OAuth2 token
feign.hystrix.enabled: false
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/patient-user?autoReconnect=true
    username: root
    password: admin
  mail:
  # Patient User will use the e-mail server configured in this section to send e-mails
    # Please configure valid e-mail server below to connect to SMTP server
    # Configure host, port, username and password per environment
    host: mail_host
    port: 25
    protocol: smtp
    username: mail_username
    password: mail_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: mail_host
  messages:
    basename: i18n/messages
c2s:
  apis:
    # Patient portal UI endpoint
    pp-ui: http://localhost/pp-ui
    scim: http://localhost:8080/uaa
  patient-user:
    config:
      pp-ui-verification-relative-path: "/fe/account/verification#emailToken="
      email-token-expiration-in-days: 7
  brand: Consent2Share
security:
  oauth2:
    client:
      client-id: patient-user
      client-secret: changeit
      access-token-uri: http://localhost:8080/uaa/oauth/token
---
# updates configuration for docker environment
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://${C2S_DB_HOST:patient-user-db.c2s.com}:${C2S_DB_PORT:3306}/patient-user?autoReconnect=true
security:
  oauth2:
    client:
      access-token-uri: http://uaa.c2s.com:8080/uaa/oauth/token
    resource:
      user-info-uri: http://uaa.c2s.com:8080/uaa/userinfo
c2s:
  apis:
    pp-ui: http://${C2S_APP_HOST:dockerhost}/pp-ui
    scim: http://uaa.c2s.com:8080/uaa
logging:
  file: /java/C2S_LOGS/patient-user/patient-user.log
  path: /java/C2S_LOGS/patient-user

---
# If the ssl spring profile below is enabled, you must follow the instructions at
# the top of this file to set your environemtn key-store and key-store-password properties as well.
spring.profiles: ssl
server:
  port: 8452
  # configure keystore and keystore password for ssl per environment
  ssl:
    # Default key-store and key-store-password
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /patientUser